apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ index .Values "app-name" }}
  namespace: argocd
  labels:
    app: {{ index .Values "app-name" }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ index .Values "app-name" }}
  template:
    metadata:
      labels:
        app: {{ index .Values "app-name" }}
    spec:
      containers:
        - name: kubia
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
