apiVersion: v1
kind: Service
metadata:
  name: {{ index .Values "name" }}-svc
  labels:
    app: {{ index .Values "name" }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ index .Values "name" }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
